-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 15:55:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apsidea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apsidea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apsidea` DEFAULT CHARACTER SET utf8 ;
USE `apsidea` ;

-- -----------------------------------------------------
-- Table `apsidea`.`agency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`agency` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`agency` (
  `id` INT NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `lat` FLOAT NULL,
  `long` FLOAT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apsidea`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`position` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`position` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apsidea`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`language` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`language` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apsidea`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`user` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`user` (
  `user_id` INT NOT NULL,
  `firstname` VARCHAR(55) NOT NULL,
  `lastname` VARCHAR(55) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `is_admin` TINYINT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `agency_id` INT NOT NULL,
  `position_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_position1_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_user_language1_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_agency`
    FOREIGN KEY (`agency_id`)
    REFERENCES `apsidea`.`agency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `apsidea`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `apsidea`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `apsidea`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`skill` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`skill` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apsidea`.`user_has_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`user_has_skill` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`user_has_skill` (
  `user_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `skill_id`),
  INDEX `fk_user_has_skills_skills1_idx` (`skill_id` ASC) VISIBLE,
  INDEX `fk_user_has_skills_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_skills_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `apsidea`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_skills_skills1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `apsidea`.`skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `apsidea`.`workflow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`workflow` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`workflow` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apsidea`.`bubble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`bubble` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`bubble` (
  `id` INT NOT NULL,
  `creator` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deadline` DATE NULL,
  `workforce` INT NULL,
  `likes` INT NULL,
  `workflow_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bubble_workflow1_idx` (`workflow_id` ASC) VISIBLE,
  INDEX `fk_bubble_user1_idx` (`creator` ASC) VISIBLE,
  CONSTRAINT `fk_bubble_workflow1`
    FOREIGN KEY (`workflow_id`)
    REFERENCES `apsidea`.`workflow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bubble_user1`
    FOREIGN KEY (`creator`)
    REFERENCES `apsidea`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `apsidea`.`user_has_bubble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`user_has_bubble` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`user_has_bubble` (
  `user_id` INT NOT NULL,
  `bubble_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `bubble_id`),
  INDEX `fk_user_has_bubble_bubble1_idx` (`bubble_id` ASC) VISIBLE,
  INDEX `fk_user_has_bubble_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_bubble_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `apsidea`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_bubble_bubble1`
    FOREIGN KEY (`bubble_id`)
    REFERENCES `apsidea`.`bubble` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `apsidea`.`keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`keyword` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`keyword` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apsidea`.`bubble_has_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`bubble_has_keyword` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`bubble_has_keyword` (
  `bubble_id` INT NOT NULL,
  `keyword_id` INT NOT NULL,
  PRIMARY KEY (`bubble_id`, `keyword_id`),
  INDEX `fk_bubble_has_keyword_keyword1_idx` (`keyword_id` ASC) VISIBLE,
  INDEX `fk_bubble_has_keyword_bubble1_idx` (`bubble_id` ASC) VISIBLE,
  CONSTRAINT `fk_bubble_has_keyword_bubble1`
    FOREIGN KEY (`bubble_id`)
    REFERENCES `apsidea`.`bubble` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bubble_has_keyword_keyword1`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `apsidea`.`keyword` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `apsidea`.`bubble_needs_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`bubble_needs_skills` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`bubble_needs_skills` (
  `bubble_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`bubble_id`, `skill_id`),
  INDEX `fk_bubble_has_skills_skills1_idx` (`skill_id` ASC) VISIBLE,
  INDEX `fk_bubble_has_skills_bubble1_idx` (`bubble_id` ASC) VISIBLE,
  CONSTRAINT `fk_bubble_has_skills_bubble1`
    FOREIGN KEY (`bubble_id`)
    REFERENCES `apsidea`.`bubble` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bubble_has_skills_skills1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `apsidea`.`skill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `apsidea`.`link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`link` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`link` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `api_key` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `apsidea`.`bubble_has_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apsidea`.`bubble_has_link` ;

CREATE TABLE IF NOT EXISTS `apsidea`.`bubble_has_link` (
  `bubble_id` INT NOT NULL,
  `link_id` INT NOT NULL,
  PRIMARY KEY (`bubble_id`, `link_id`),
  INDEX `fk_bubble_has_zelda_zelda1_idx` (`link_id` ASC) VISIBLE,
  INDEX `fk_bubble_has_zelda_bubble1_idx` (`bubble_id` ASC) VISIBLE,
  CONSTRAINT `fk_bubble_has_zelda_bubble1`
    FOREIGN KEY (`bubble_id`)
    REFERENCES `apsidea`.`bubble` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bubble_has_zelda_zelda1`
    FOREIGN KEY (`link_id`)
    REFERENCES `apsidea`.`link` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
